export const ApiConfig ={
    userRegister:{
        method:"post",
        url:"v1/user/register"
    },
    userLogin:{
        method:"post",
        url:"v1/user/login"
    },
    leaderboardList:{
        method:"post",
        url:"v1/user/leaderboard"
    },
    newActivitiesList:{
        method:"post",
        url:"v1/user/new-activities"
    },
    activityComplete:{
        method:"post",
        url:"v1/user/activity/complete"
    },
    myActivityList:{
        method:"post",
        url:"v1/user/my-activity/list"
    },
    userActivityList:{
        method:"post",
        url:"v1/user/activity/list"
    },
    userDetailsGet:{
        method:"get",
        url:"v1/user/details/get"
    },
}